name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    name: "Test GraphQL & REST APIs"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Rodar testes GraphQL
      run: npm run test:graphql

    - name: Rodar testes REST
      run: npm run test:rest

    - name: Rodar teste de fluxo completo
      run: npm run test:fluxo

    - name: Rodar todos os testes
      run: npm test